modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
[[mods]]
modId="end_respawn_anchor"
version="1.0"
displayName="EndRespawnAnchor"
authors="Mikndesu"
credits="Credit for awesome textures goes to rosieholstein"
description='''
The EndRespawnAnchor is used to respawn in the End.
Remember you will always be resurrected in the End,
no matter where you die.
'''
[[dependencies.end_respawn_anchor]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"
[[dependencies.end_respawn_anchor]]
modId="minecraft"
mandatory=true
versionRange="[1.19, 1.20)"
ordering="NONE"
side="BOTH"