modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
[[mods]]
modId="end_respawn_anchor"
version="1.0"
displayName="EndRespawnAnchor"
authors="Mikndesu"
credits="Credit for awesome texture goes to rosieholstein"
description='''
This mod adds one block, "End Respawn Anchor"  
By this anchor, your respawn position is basically where anchor is unless anchor is charged,  
but only when you use End Portal to Overworld, you will respawn where your previous respawn  
position was.
'''
[[dependencies.end_respawn_anchor]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"
[[dependencies.end_respawn_anchor]]
modId="minecraft"
mandatory=true
versionRange="[1.19, 1.20)"
ordering="NONE"
side="BOTH"